---
title: "Final Project Data Processing"
author: "CDT Joshua Wong"
date: "2024-04-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/adrian.pimentel/OneDrive - West Point/AY24-2/MA478/Final Project/Data")


```

### Import Libraries

```{r}
library(tidyverse)
# for glms
library(faraway)
# for zip glms
library(pscl)
# linear mixed effects models
library(lme4)
library(nlme)
setwd("C:/Users/adrian.pimentel/OneDrive - West Point/AY24-2/MA478/Final Project/Data")


```

### Import Data

```{r}
# Must Set First, WD Reset for every chunk
setwd("C:/Users/adrian.pimentel/OneDrive - West Point/AY24-2/MA478/Final Project/Data")
all <- read.csv("alldata.csv")
crime <- read.csv("crime .csv")
#Population by Census Block Group
pop <- read.csv("pop.csv")
#Percentage Unemployed by Census Block Group
unemp <- read.csv("unemp.csv")
#Centered and Scaled Average Family Income by Census Block Group (2015 Dollars)
wealth <- read.csv("wealth.csv")
#Number of Young Males by Census Block Group (15-20 yr olds)
ym <- read.csv("ym.csv")
neigh <- readMM("neighborhood.mtx")

pop <- pop %>% rename(pop = x)
wealth <- wealth %>% rename(wealth = x)
unemp <- unemp %>% rename(unemp = x)
ym <- ym %>% rename(ym = x)
```
### Data Processing

```{r}
library(reshape2)
long <- melt(all, id.vars=c("Column1", "wealth", "unemployment", "Population", "young_males"))
colnames(long)[colnames(long) == 'value'] <- 'Burglaries'
colnames(long)[colnames(long) == 'Column1'] <- 'Block'

# Add Month and Year and date Variables
long$year <- substr(long$variable, 7, 10)
long$month <- substr(long$variable, 11, 13)
long$date <- substr(long$variable, 7, 13)


# Rename other census block variables
long <- long %>% 
  rename(pop = Population) %>% 
  rename(unemp = unemployment) %>% 
  rename(ym = young_males) %>% 
  rename(target = Burglaries) %>% 
  rename(block = Block)


# Add percent Young males variable
long$perc_ym <- long$ym / long$pop

# Take away uneeded col
long <- subset(long, select = -ym)
long <- subset(long, select = -date)
# long <- subset(long, select = -variable)

# make variables right type
long$year <- as.integer(long$year) - 2010
long$month <- as.factor(long$month)

# scale variables
long[, c("pop", "unemp", "perc_ym")] <- scale(long[, c("pop", "unemp", "perc_ym")])

str(long)
```
```{r}
crime2 <- apply(crime, 2, sum)

# Sum over census blocks (see variation over month)
crime3 <- data.frame(val=crime2)
crime3 <- slice(crime3, -1)
crime3$name <- row.names(crime3)

# Add an index column
crime3 <- crime3 %>% mutate(index = row_number())

# Add Month and Year and date Variables
crime3$year <- as.integer(substr(crime3$name, 7, 10))
crime3$month <- as.integer(substr(crime3$name, 11, 13))

library(ggplot2)

# Define custom color palette
custom_colors <- c("#d7bde2","#8e44ad")

# Create the plot
graph1 <- ggplot(crime3, aes(x = index, y = val)) +
  geom_point(color = custom_colors[1], size = 3) + 
  labs(title = "Total Burglaries in Chicago Over 72 Months (2010-2015)",
       x = "Month (1-72)",
       y = "Total Burglaries in Chicago") +
  theme_minimal() +  
  theme(legend.position = "none",  # Remove legend
        panel.grid.major = element_blank(),  # Remove major gridlines
        panel.grid.minor = element_blank(),  # Remove minor gridlines
        axis.line = element_line(color = "black"),  # Set axis lines color
        text = element_text(family = "Arial", size = 12, color = "black"),  # Set font family, size, and color
        plot.title = element_text(hjust = 0.5))  # Center plot title

# Display the plot
graph1


graph2 <- ggplot(crime3, aes(x = month, y = val)) +
  geom_point() +
  geom_smooth(method = lm, col = 'blue')
  labs(title = "Total Burglaries in Chicago Per Year",
       x = "Month (1-12)",
       y = "Total Burglaries in Chicago")
plot_all2 <- ggplot(long, aes(x = young_males, y = sum_count)) +
  geom_point(color = "#d7bde2", size = 3) +  # Customize point color and size
  geom_smooth(method = "lm", se = FALSE, color = "#8e44ad") +  # Add linear regression line
  labs(title = "Relationship Between Young Males and Total Burglaries",
       x = "Young Males",
       y = "Total Burglaries") +
  theme_minimal() +  # Use a minimal theme
  theme(legend.position = "none",  # Remove legend
        panel.grid.major = element_blank(),  # Remove major gridlines
        panel.grid.minor = element_blank(),  # Remove minor gridlines
        axis.line = element_line(color = "black"),  # Set axis lines color
        text = element_text(family = "Arial", size = 12, color = "black"),  # Set font family, size, and color
        plot.title = element_text(hjust = 0.5))  # Center plot title

# Display the plot
plot_all2
  
library(ggplot2)

# Create the histogram
histogram_young_males <- ggplot(long, aes(x = ym)) +
  geom_histogram(binwidth = 10, fill = "#d7bde2", color = "black", alpha = 0.8) +  # Customize histogram aesthetics
  labs(title = "Distribution of Young Males per Census Block",
       x = "Frequency",
       y = "Number of Young Males") +
  theme_minimal() +  # Use a minimal theme
  theme(legend.position = "none",  # Remove legend
        panel.grid.major = element_blank(),  # Remove major gridlines
        panel.grid.minor = element_blank(),  # Remove minor gridlines
        axis.line = element_line(color = "black"),  # Set axis lines color
        text = element_text(family = "Arial", size = 12, color = "black"),  # Set font family, size, and color
        plot.title = element_text(hjust = 0.5))  # Center plot title

# Display the histogram
histogram_young_males

histogram_sum_count <- ggplot(long, aes(x = target)) +
  geom_histogram(binwidth = 1, breaks = seq(0, 10, by = 1),  # Specify breaks for bins between 0 and 10
                 fill = "#d7bde2", color = "black", alpha = 0.8) +  # Histogram aesthetics
  labs(title = "Distribution of Burglaries by Census Block in a Month",
       x = "Burglaries in Month",
       y = "Frequency") +
  scale_x_continuous(breaks = seq(0, 10, by = 1)) +  # Ensure integer-only axis labels
  theme_minimal() +  # Use a minimal theme
  theme(legend.position = "none",  # Remove legend
        panel.grid.major = element_blank(),  # Remove major gridlines
        panel.grid.minor = element_blank(),  # Remove minor gridlines
        axis.line = element_line(color = "black"),  # Set axis lines color
        text = element_text(family = "Arial", size = 12, color = "black"),  # Set font family, size, and color
        plot.title = element_text(hjust = 0.5))

# Display the histogram without density estimate
histogram_sum_count

```
```{r}
# Find columns starting with "count."
count_cols <- names(all)[startsWith(names(all), "count.")]

# Sum the values across selected columns for each row
all$sum_count <- rowSums(all[count_cols])

all2 <- all[c("Column1", "sum_count", "young_males", "wealth", "unemployment", "Population")]

plot1 <- all2 %>% ggplot(aes(x=young_males, y=sum_count)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

plot2 <- all2 %>% ggplot(aes(x=wealth, y=sum_count)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

plot3 <- all2 %>% ggplot(aes(x=unemployment, y=sum_count)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

plot4 <- all2 %>% ggplot(aes(x=Population, y=sum_count)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

plot1
plot2
plot3
plot4
```
```{r}
library(ggplot2)

plot1 <- ggplot(long, aes(x = pop, y = wealth)) +
  geom_point(color = "#d7bde2", size = 3) + 
  geom_smooth(method = "lm", se = FALSE, color = "#8e44ad") +
  labs(title = "Relationship between population and wealth",
       x = "Population",
       y = "Wealth") +
  theme_minimal() +  # Use a minimal theme
  theme(legend.position = "none",  # Remove legend
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(color = "black"), 
        text = element_text(family = "Arial", size = 12, color = "black"),  
        plot.title = element_text(hjust = 0.5)) +  
  coord_cartesian(ylim = c(-0.05, 0.1))  

# Display the plot
print(plot1)

# Display the plot
print(plot1)


plot2 <- ggplot(long, aes(x = pop, y = wealth)) +
  geom_point(color = custom_colors[1], size = 3) +  # Customize point color and size
  geom_smooth(method = "lm", se = FALSE, color = custom_colors[2]) +  # Customize smoothing line color
  labs(title = "Relationship Between Population and Wealth",
       x = "Population",
       y = "Wealth") +
  theme_minimal() +  # Use a minimal theme
  theme(legend.position = "none",  # Remove legend
        panel.grid.major = element_blank(),  # Remove major gridlines
        panel.grid.minor = element_blank(),  # Remove minor gridlines
        axis.line = element_line(color = "black"),  # Set axis lines color
        text = element_text(family = "Arial", size = 12, color = "black"),  # Set font family, size, and color
        plot.title = element_text(hjust = 0.5))  # Center plot title

# Display the plot
plot2


plot1
plot2
```

```{r}
target_zero <- long[long$target == 0, ]
target_gtzero <- long[long$target > 0, ]

plot1 <- target_zero %>% ggplot(aes(x=pop, y=target)) +
  geom_point()

plot2 <- target_gtzero %>% ggplot(aes(x=pop, y=target)) +
  geom_point()


plot3 <- ggplot(long, aes(x = pop, y = target)) +
  geom_point(aes(color = factor(target == 0)), size = 3) +  # Differentiate colors based on target value
  scale_color_manual(values = c("#ff9999", "#99ff99"), labels = c("Burglaries", "No Burglaries")) +  # Assign colors to the legend
  labs(title = "Relationship Between Population and Burglaries",
       x = "Population",
       y = "Number of Burglaries") +
  theme_minimal() +  # Use a minimal theme
  theme(legend.title = element_blank(),  # Remove legend title
        panel.grid.major = element_blank(),  # Remove major gridlines
        panel.grid.minor = element_blank(),  # Remove minor gridlines
        axis.line = element_line(color = "black"),  # Set axis lines color
        text = element_text(family = "Arial", size = 12, color = "black"),  # Set font family, size, and color
        plot.title = element_text(hjust = 0.5))

plot3

plot1
plot2
plot3
```


### Models

### Poisson GLM

```{r}
pois_glm <- glm(target~perc_ym+pop+unemp+year+month, data=long, family=poisson)
summary(pois_glm)
```
```{r}
# Goodness of fit test for poisson glm 1 (our model compared to saturated)
1-pchisq(deviance(pois_glm), df.residual(pois_glm))
```
```{r}
halfnorm(residuals(pois_glm))
```
```{r}
plot(log(fitted(pois_glm)), log((long$target-fitted(pois_glm))^2),
     xlab=expression(hat(mu)), ylab=expression((y-hat(mu))^2))
abline(0, 1)
```
```{r}
# Estimate phi
deviance(pois_glm) / df.residual(pois_glm)
sum(residuals(pois_glm, type="pearson")^2)/pois_glm$df.res
```
### Zip GLM

```{r}
zip_glm <- zeroinfl(target~perc_ym+pop+unemp+year+month, 
                    data=long, 
                    dist="poisson")
summary(zip_glm)
```

```{r}
# Fit zero-inflated Poisson model with different predictors for each component
zip_glm2 <- zeroinfl(target ~ perc_ym + pop + unemp + year + month | perc_ym + pop + unemp, 
                    data = long, 
                    dist = "poisson")
summary(zip_glm2)
```

```{r}
AIC(pois_glm)
AIC(zip_glm)
AIC(zip_glm2)
```

### Generalized Mixed Effects Models

## Linear Mixed Effects Model

```{r}
start_time <- Sys.time()
glmer_model <- glmer(target~perc_ym+pop+unemp+(1|variable), nAGQ=25, family=poisson, data=long)
summary(glmer_model)

end_time <- Sys.time()
end_time - start_time
```
```{r}
start_time <- Sys.time()
glmer_model <- glmer(target~perc_ym+pop+unemp+(1|block) + (1|variable), nAGQ=1, family=poisson, data=long)
summary(glmer_model)
end_time <- Sys.time()
end_time - start_time
AIC(glmer_model)
```
```{r}
#residual analysis
#poisson
plot(residuals(pois_glm1), ylab = 'Residuals', xlab = 'observation index', main = 'Residuals of Poisson model')
#zipmod
plot(residuals(zip_glm2), ylab = 'Residuals', xlab = 'observation index', main = 'Residuals of Zero-inflated Poisson model')
plot(residuals(pois_glm3), ylab = 'Residuals', xlab = 'observation index', main = 'Residuals of Generalized mixed effects  model')
qqnorm(resid(pois_glm))
```

